services:
  webbaharihook:
    build:
      context: .
      dockerfile: Dockerfile
    image: webbaharihook:latest
    container_name: webbaharihook-app
    ports:
      - "127.0.0.1:3000:3000"  # Only bind to localhost
    environment:
      DATABASE_URL: ${DATABASE_URL}
      NEXTAUTH_URL: https://${DOMAIN:-webbaharihook2.baharihari.com}
      NEXTAUTH_SECRET: ${NEXTAUTH_SECRET}
      NODE_ENV: production
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:3000/api/health', (res) => { process.exit(res.statusCode === 200 ? 0 : 1); });"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s