services:
  webbaharihook:
    build:
      context: .
      dockerfile: Dockerfile
    image: webbaharihook:latest
    container_name: webbaharihook-app
    ports:
      - "3000:3000"
    environment:
      # Database configuration - use your external MySQL
      DATABASE_URL: ${DATABASE_URL}

      # NextAuth configuration
      NEXTAUTH_URL: ${NEXTAUTH_URL:-http://localhost:3000}
      NEXTAUTH_SECRET: ${NEXTAUTH_SECRET}

      # Node environment
      NODE_ENV: ${NODE_ENV:-production}

    restart: unless-stopped
    networks:
      - webbaharihook-network
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:3000/api/health', (res) => { process.exit(res.statusCode === 200 ? 0 : 1); });"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  webbaharihook-network:
    driver: bridge

# Production deployment with external MySQL
# Make sure to set these environment variables:
# - DATABASE_URL: Your external MySQL connection string
# - NEXTAUTH_SECRET: Your NextAuth secret key
# - NEXTAUTH_URL: Your production URL